Updating Founded by text
litmuschaos/website-litmuschaos pull request #145
Opened 2021-04-09 09:22 UTC by S-ayanide

## Changes

Updating Founded by text

Signed-off-by: Sayan Mondal <sayan@chaosnative.com>

2021-04-09 09:22 UTC, gdsoumya submitted a review, later dismissed

2021-04-09 10:13 UTC, arkajyotiMukherjee approved these changes

2021-04-09 10:13 UTC, arkajyotiMukherjee commented on src/components/footer/Footer.tsx
>              &nbsp;❤️
The heart was also to me removed maybe...can you check

2021-04-09 10:41 UTC, arkajyotiMukherjee requested changes

2021-04-09 10:41 UTC, arkajyotiMukherjee commented on src/components/texts/Texts.tsx
> +  text-decoration: ${(props) => (props.underline ? "underline" : "none")};
These two properties are be required...you can wrap the PurpleText in an anchor tag, then cursor will automatically be pointer and text-decoration can be set to none.

2021-04-09 10:41 UTC, arkajyotiMukherjee commented on src/components/sections/chaoshub/WhyChaoshub.tsx
>              target="_blank"
This anchor tag can be given a style...or rather you can give the style in index.css to make all anchor tags to not have an underline.

2021-04-09 12:29 UTC, amityt submitted a review, later dismissed

2021-04-12 04:08 UTC, amityt approved these changes

2021-04-12 04:21 UTC, merged